# named volumes:
volumes:
  max-plumber:
services:
  db:
    image: "mariadb:latest"
    volumes:
      # without volumes, data would be reset everytime
      # named volumes:
      - max-plumber:/var/lib/mysql
      # local volumes
#      - ./conf/mysql:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  app:
    image: php:8.1-apache
    # build specifies the location of a custom Dockerfile
    build: ./
    container_name: max-plumber
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - max-plumber:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      MYSQL_HOST: "db"
      MYSQL_DATABASE: ""
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}





